### ISSUE TITLE
How to integrate ADAL Azure with out cocoapods, Please provide the steps 

### ISSUE THREAD

**Issue by sudhakarmallidi** [OneDrive/onedrive-sdk-ios#1]

**Comment by aclev** [comment]
Hi @sudhakarmallidi, 
Thanks for your question! We strongly recommend using cocoapods to integrate with the OneDriveSDK, it should handle all the decencies with ADAL for you. Are you trying to include the OneDrive SDK from source? Can you provide some more details of your scenario?

**Comment by James24** [comment]
HI @sudhakarmallidi,
Download ADAL from https://github.com/AzureAD/azure-activedirectory-library-for-objc/archive/master.zip 

and import the following files in your project https://github.com/AzureAD/azure-activedirectory-library-for-objc/tree/master/ADALiOS/ADALiOS

**Comment by baoshiwei** [comment]
My issue is the same.Just  pod install,the ADAL not work

**Comment by aclev** [comment]
Closing the issue, please re-open if you are still having the problem.
