### ISSUE TITLE
Difference between this sdk and msgraph sdk?

### ISSUE THREAD

**Issue by gerchicov-bp** [OneDrive/onedrive-sdk-ios#103]
I need to add support for OneDrive in my app but I see **2! official sdks**.

Could you explain what is the difference from this repository?

https://github.com/microsoftgraph/msgraph-sdk-ios.git

The methods are similar and both sdks are official and from Microsoft.

And finally I think you should add the answer into your readme file.

**Comment by kevklam** [comment]
Microsoft Graph is a unified API exposing functionality from across all of Microsoft's online services. The Graph SDK is a client library for the Graph API, meaning you can use it to manage calendar, contacts, email etc. in addition to managing OneDrive files.

The OneDrive SDK is a client library for the OneDrive API, which is specifically for managing OneDrive files.

In terms of OneDrive usage, there are some differences between the two APIs (and therefore the two SDK's). For the most part the Graph API simply proxies to the OneDrive API, and therefore the method signatures/calling pattern are very similar. However the Graph API generally lags behind the OneDrive API for some period of time, so the latest API updates may be available in the OneDrive SDK before Graph. Additionally, there are differences in how app registration and authentication works that I won't get into here (but you can compare the relevant documentation).

I will do as you suggest and add an explanation to the README!
