### ISSUE TITLE
How to upload a file/folder into a concrete path?

### ISSUE THREAD

**Issue by gerchicov-bp** [OneDrive/onedrive-sdk-ios#104]
I have a folder which may contain inner folders and files. And I need to upload it.

Doesn't SDK support folder uploading? Ok. I'll iterate through all the inner folders and files. But there are linked problems: I can't just use folder path - I need somehow to iterate between folders and files, to check if file/folder exists, to create folders which don't exist and to retrieve and assign their IDs...

How do you solve this issue?

**Comment by kevklam** [comment]
Unfortunately we do not have a sample for this at the moment. There are many different possible strategies for what to do when a file already exists.

Here's some tools that may be helpful:
- You can use the 'itemByPath' API to attempt to get the folder you are interested in, to see if it exists.
- You can specify to expand children on a given item, if you are only expecting the folder hierarchy to go 1 level deep.
- You can use 'delta' to pull down the complete hierarchy of children under a folder and then use this information to perform a folder diff: https://github.com/OneDrive/onedrive-api-docs/blob/master/items/view_delta.md
- When uploading a file, you can specify what behavior to use on name conflict (replace, rename, fail). This will be a method on the Request object.

**Comment by spacemonkey92** [comment]
Can you tell me how to create a folder using the sdk ?
