### ISSUE TITLE
How "Sign In" more than one account?

### ISSUE THREAD

**Issue by DimonDeveloper** [OneDrive/onedrive-sdk-ios#106]
If one account already "Sign In" and use [ODClient authenticatedClientWithCompletion:^(ODClient *client, NSError *error)
I have this:
![img_0192](https://cloud.githubusercontent.com/assets/3527457/15807313/8ad669d2-2b63-11e6-90cf-2a5103287297.PNG)

I need to this for "Sign In" next account:
![img_0193](https://cloud.githubusercontent.com/assets/3527457/15807318/9fbd7836-2b63-11e6-9368-4e431cf5f97b.PNG)

There is a way for the login by ID even if ID already log out?

**Comment by kevklam** [comment]
Hi @DimonDeveloper, unfortunately we don't support multiple simultaneous users right now. Can you explain more about your scenario that requires this functionality?

**Comment by DimonDeveloper** [comment]
HI @kevklam My app can work with cloud storages (download, upload, share etc.). If the user need to enter more than one account OneDrive I should give him that opportunity.

**Comment by kevklam** [comment]
If it is critical to your app, you may be able to get the behavior you want by selectively clearing cookies in NSHTTPCookieStorage before login (or clear all of them to be sure, though that will remove cached credentials for all other services too). However, this scenario has not been tested in the SDK as it is not supported functionality. Additionally, we can't make any guarantees on forward compatibility depending on how the authentication API evolves.

Please reopen this issue if you need additional assistance.

Thanks,
Kevin

**Comment by DimonDeveloper** [comment]
`NSHTTPCookieStorage *cookieStorage = [NSHTTPCookieStorage sharedHTTPCookieStorage];  
for (NSHTTPCookie *each in cookieStorage.cookies) {
[cookieStorage deleteCookie:each];
        }`

@kevklam This has helped to add a new account but the second replaced the first. And now i can not "Sign In" in the first account.

If i check `[ODClient loadClients];` it's shows array only with second account.

**Comment by kevklam** [comment]
I don't have time to investigate adding this support right now, but if you want to try debugging the issue yourself you may want to put breakpoints in ODAccountStore.m in the following places:

``` objc
// in -(NSArray*)loadAccounts - breakpoint and inspect dictionary:
NSDictionary *dictionary = [NSKeyedUnarchiver unarchiveObjectWithFile:self.accountStorePath];

// in -(void)storeAccounts - breakpoint, inspect self.accountSessions, step through and verify that 'accounts' and 'allAccounts' get populated correctly
NSMutableDictionary *allAccounts = [NSMutableDictionary dictionary];
```

**Comment by longleeproduction** [comment]
> `NSHTTPCookieStorage *cookieStorage = [NSHTTPCookieStorage sharedHTTPCookieStorage]; for (NSHTTPCookie *each in cookieStorage.cookies) { [cookieStorage deleteCookie:each]; }`
---> It's working very well. Thank you.

> If i check `[ODClient loadClients];` it's shows array only with second account.
---> I think after login you need call function: `[ODClient setCurrentClient:client];`
