### ISSUE TITLE
Tapping twice on allow permissions button causes error

### ISSUE THREAD

**Issue by spencer-microsoft** [OneDrive/onedrive-sdk-ios#109]
If the user signs in successfully and is presented with the permissions list ("Let this app access your info?") and taps on the "Yes" button twice, it always dismisses the controller and fails with an error.

**Error**
"OneDrive SDK ERROR : Error reading code from response"
"The operation couldn’t be completed. (com.microsoft.onedrivesdk.autherror error 1.)"
"ODAuthErrorKey" : "https://login.live.com/oauth20_desktop.srf?error=server_error&lc=1033"

**Comment by spencer-microsoft** [comment]
![simulator screen shot jun 7 2016 5 26 31 pm](https://cloud.githubusercontent.com/assets/17574361/15879012/fa94fd7a-2cd4-11e6-9488-d98b5d0fe0a9.png)
Recreated the issue in the example project

**Comment by kevklam** [comment]
Will forward to the ID team. I attempted a workaround for this by adding a couple seconds of hysteresis on form submission in shouldStartLoadWithRequest, but apparently that blocks the redirect hop immediately afterward.

**Comment by kevklam** [comment]
Closing issue here as it is being tracked internally by ID team
