### ISSUE TITLE
Feature request. Handle task cancel state before executing of completion block

### ISSUE THREAD

**Issue by gerchicov-bp** [OneDrive/onedrive-sdk-ios#110]
Response doesn't contain `ODURLSessionTask` param so I need to write additional code to handle cancel states. The reason is if you run mostly one task per time then `-[ODURLSessionTask cancel]` by default is useless - it has influence only if the task is not executed yet.
Any "Cancel" visual buttons by default are useless too because you can't cancel the current operation.

**Comment by kevklam** [comment]
Please clarify this request. Which methods are not returning an appropriate ODURLSessionTask?

**Comment by gerchicov-bp** [comment]
Sorry the trouble was with my code
