### ISSUE TITLE
Bug with timeout on requesting item collection

### ISSUE THREAD

**Issue by gerchicov-bp** [OneDrive/onedrive-sdk-ios#111]
Every request may cause authentication error. And it requires enough much code to handle authentication error in each request completion block.

**Comment by kevklam** [comment]
Please refer to comment in other issue regarding authentication error. I believe this is because of your local change to the auth completion flow. In its unmodified state the SDK should always have a valid auth or refresh token, and when the auth token expires will automatically perform refresh.

**Comment by gerchicov-bp** [comment]
I have found a solution but it doesn't involves code. I just changed the app id in `+[ODClient setMicrosoftAccountAppId:scopes:]` to a new one. The old key looks like your one in examples (but the numbers are different) and the new key is totally different because it is longer and includes hyphens/dashes.
So what is the difference for the application when I just change this key? Does it use another api or sends requests to another server?

**Comment by gerchicov-bp** [comment]
Finally the different key works better but it doesn't completely resolve the trouble with frequent timeout errors

**Comment by kevklam** [comment]
Is the timing out a separate issue from the authentication errors? When do the timeouts occur, during authentication or when making other requests?

Regarding app ID, the app registration endpoint has made some changes recently and one of the differences is that newly created apps get the new type of key (with hyphens). It still makes requests against the same servers, but processing the ID will go through a different code path. It seems unlikely that changing the app Id would make a difference, but it's possible.

**Comment by gerchicov-bp** [comment]
sorry I'm out of time. I'll try it later. But anyways it happens frequently with the key from you example

**Comment by kevklam** [comment]
Are you still having issues with timeouts? Can you provide more information on what operations cause timeouts?

**Comment by gerchicov-bp** [comment]
I haven't used the old key so it doesn't occur so often. But timeouts occur at very random random requests. I can list the requests I have in my app only:
- login
- get items in folder
- download
- upload
- delete
