### ISSUE TITLE
Feature request. Download multiple files and folders?

### ISSUE THREAD

**Issue by gerchicov-bp** [OneDrive/onedrive-sdk-ios#113]
As I understand API doesn't include this feature and this sdk can't do this too

**Comment by kevklam** [comment]
What is your desired behavior? Downloads via HTTP GET operate on single files.

**Comment by gerchicov-bp** [comment]
Ok, I speak about something like the following:

```
NSArray *arr = ...; //item ids
[[[[self.od_client drive] items:arr] contentRequest] downloadWithIntermediateCompletion:^(NSURL *location, NSURLResponse *response, NSError *error)^{...}
fullCompletion:^(NSURL *location, NSURLResponse *response, NSError *error)^{...}]
```

You pass to library an array of items (for example item ids/paths) and two blocks - first block is called after the downloading of each file the second block is called after the downloading of the whole item collection. Maybe the similar method is needed for uploading

**Comment by kevklam** [comment]
We have been considering creating a library of extensions to make tasks like this more convenient - I will add this to the list of suggestions if we do produce such a library. In its current state though, the SDK is mostly just a client library with 1:1 mappings between the requestbuilder/request pattern and direct API calls so such a modification is not suitable for inclusion (the request/requestbuilders are automatically generated from the service EDMX description).
