### ISSUE TITLE
Feature request. Download into the specified path

### ISSUE THREAD

**Issue by gerchicov-bp** [OneDrive/onedrive-sdk-ios#114]
Currently the library defines by itself where to store the file. Then app should move the file by itself.

What about to mix 2 actions into one - download to the specified path at once?

**Comment by kevklam** [comment]
Download uses [NSURLSessionDownloadTask](https://developer.apple.com/library/ios/documentation/Foundation/Reference/NSURLSessionDownloadTask_class/) behind the scenes, which stores the file in a temporary location.

**Comment by gerchicov-bp** [comment]
ok, what about to add additional param "save path" which will allow to library to move a file to the desired folder by itself without extra code in app?
