### ISSUE TITLE
Handle removed resource?

### ISSUE THREAD

**Issue by gerchicov-bp** [OneDrive/onedrive-sdk-ios#115]
`Error Domain=NSURLErrorDomain Code=-1100 "Запрошенный URL на этом сервере не обнаружен." UserInfo=0x19eabf30 {NSErrorFailingURLKey=https://api.onedrive.com/v1.0/drive/items/97C820BCD766E514!172/content, NSErrorFailingURLStringKey=https://api.onedrive.com/v1.0/drive/items/97C820BCD766E514!172/content, NSLocalizedDescription=Запрошенный URL на этом сервере не обнаружен.}`

Steps to reproduce:
1)get id of the file
2)delete this file (not definitely via this app)
3)request to download this file

Result - "download error" is returned as desired. But all the methods from `NSError+OneDriveSDK.h` return `NO` and `nil` and I must handle this error manually by using this code "-1100" only.

**Comment by kevklam** [comment]
Test case:

``` objc
        NSString *str = @"test file";
        NSData *data = [NSData dataWithBytes:[str UTF8String] length:[str length]];
        [[[[[self.client drive] items:@"root"] itemByPath:@"blahtest/asdf3.txt"] contentRequest] uploadFromData:data completion:^(ODItem *response, NSError *error) {
            if (error) {
                NSLog(@"Ooops failed to create file");
            }
            else
            {
                __block NSString *itemid = response.id;
                [[[[self.client drive] items:itemid] request] deleteWithCompletion:^(NSError *error) {
                    if (error) {
                        NSLog(@"Ooops failed to delete file");
                    }
                    else
                    {
                        [[[[self.client drive] items:itemid] request] getWithCompletion:^(ODItem *response, NSError *error) {
                            NSLog(@"Error: %@, isClientError: %d", error, [error isClientError]);
                        }];
                    }
                }];
            }
        }];

```

Output:

> 2016-06-10 17:37:43.880 iOSExplorer[49491:31028171] Error: Error Domain=com.microsoft.onedrive.errors Code=404 "not found" UserInfo={error= itemNotFound : Item does not exist, NSLocalizedDescription=not found}, **isClientError: 1**

**Comment by gerchicov-bp** [comment]
Yes, but `getWithCompletion:` returns just general info about file. I  meaned **request to download** this file: `downloadWithCompletion:`

**Comment by kevklam** [comment]
Updated test case:

``` objc
        NSString *str = @"test file";
        NSData *data = [NSData dataWithBytes:[str UTF8String] length:[str length]];
        [[[[[self.client drive] items:@"root"] itemByPath:@"blahtest/asdf3.txt"] contentRequest] uploadFromData:data completion:^(ODItem *response, NSError *error) {
            if (error) {
                NSLog(@"Ooops failed to create file");
            }
            else
            {
                __block NSString *itemid = response.id;
                [[[[self.client drive] items:itemid] request] deleteWithCompletion:^(NSError *error) {
                    if (error) {
                        NSLog(@"Ooops failed to delete file");
                    }
                    else
                    {
                        [[[[self.client drive] items:itemid] contentRequest] downloadWithCompletion:^(NSURL *location, NSURLResponse *response, NSError *error) {
                            NSLog(@"Error: %@, isClientError: %d", error, [error isClientError]);
                        }];
                    }
                }];
            }
        }];
```

Output:

> 2016-06-15 15:31:29.577 iOSExplorer[6592:408496] Error: Error Domain=com.microsoft.onedrive.errors Code=404 "not found" UserInfo={error= malformed : (null), NSLocalizedDescription=not found}, isClientError: 1

Are you attempting to perform downloadWithCompletion on the item itself? This is not a valid operation, download must be performed on the contentRequest.

**Comment by gerchicov-bp** [comment]
I have the same code and just few days ago it gave an undefined error I mentioned above. So it was server error and now I should close issue
