### ISSUE TITLE
Can't import via cocoapods

### ISSUE THREAD

**Issue by Gargo** [OneDrive/onedrive-sdk-ios#117]
podfile:

```
target '...'
pod 'OneDriveSDK'
```

Unable to find a specification for `OneDriveSDK`

**Comment by kevklam** [comment]
Sounds like your cocoapods spec repo got out of date somehow - Try 'pod setup' and see if that fixes the issue for you.

**Comment by Gargo** [comment]
almost and it is doesn't depends on this repository only. "pod setup" is not enough. I used:

```
pod repo remove master
pod setup
pod install
```

but anyways I can't understand what was the mistake
