### ISSUE TITLE
Cannot login using iOS 9

### ISSUE THREAD

**Issue by ceecbrookes** [OneDrive/onedrive-sdk-ios#12]
After calling `authenticatedClientWithCompletion:` and entering email address, I get redirected to a blank screen (within the login popover). I can successfully login using the same code with iOS 8.

**Comment by aclev** [comment]
Hi @ceecbrookes Thanks for reporting this issue.  I am investigating now.

**Comment by aclev** [comment]
@ceecbrookes, does this happen for both OneDrive for Business and Personal? What type of account did you try to login with?

**Comment by ceecbrookes** [comment]
I tried to log in with a personal account. Thanks for investigating @aclev.

**Comment by vincenttsai** [comment]
I think it's the transport security in iOS9 , you can try to add the following in the info.plist to see if this works.
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>

**Comment by aclev** [comment]
Hi @vincenttsai and @ceecbrookes That is correct that it is the transport security in iOS 9.  Please take a look at the readme for instructions on how to disable it.  Disabling ATS altogether (like shown above) is not the recommended approach.

**Comment by vincenttsai** [comment]
@aclev Thanks for your information.

**Comment by ceecbrookes** [comment]
@vincenttsai / @aclev, this solves the issue, thanks for your time.
