### ISSUE TITLE
How to use refresh_token (refreshToken in app)?

### ISSUE THREAD

**Issue by gerchicov-bp** [OneDrive/onedrive-sdk-ios#121]
According to documentation I can use this token instead of requesting username and password:
https://dev.onedrive.com/auth/msa_oauth.htm
How to use it in this sdk? There is no info about it

**Comment by kevklam** [comment]
If you're referring to the token you get by clicking "Get Token", this is a temporary token for experimenting with the API. You can use something like Fiddler/Charles to craft an HTTP request using this token for authentication.

**Comment by gerchicov-bp** [comment]
I mean I was asked why users should relogin too frequently with new sdk (I just take them to login page when the app gets auth error). But in the same time I read that there is `refresh_token` in new API which maybe allows to "relogin" user without of requesting username and password again.
So did I write a correct code and sdk doesn't allow to "keep the auth session" for a long time? Or are there any ways to achieve the same result?

As I understand I need to somehow access to method `- (void)refreshAndStoreAccountSession:(ODAccountSession *)session withCompletion:(void (^)(NSError *error))completionHandler`. But it is a little strange - it represents a "request task" but doesn't return "task object" which I need to have a possibility to cancel the current task.

**Comment by kevklam** [comment]
This should have been handled automatically by the SDK, it sounds like a bug either in the SDK or in the service (perhaps the refresh token is not being returned as it should be). I don't have time to debug this right now, but will mark it for investigation.

**Comment by gerchicov-bp** [comment]
Could it be fixed if I simply set the expiration date of the session to 1 hour (currently it is 1 day)?

**Comment by kevklam** [comment]
The expiration date returned by the service is for informational purposes only. The access token will not work to authenticate requests after it has expired.

**Comment by kevklam** [comment]
Please specify the 'offline_access' scope when configuring auth. For example:

``` objc
[ODClient setMicrosoftAccountAppId:@"04ed648a-b08d-4e68-a12e-404599d071f7" scopes:@[@"onedrive.readwrite,offline_access"]];
```
