### ISSUE TITLE
Can't find Adal Headers

### ISSUE THREAD

**Issue by chaseholland** [OneDrive/onedrive-sdk-ios#123]
ADALiOS headers are imported as user headers instead of framework headers. 

ie `#import "ADUserInformation.h"`

instead of `#import <ADALiOS/ADUserInformation.h>`

which causes issues when linking this as a pod. A temporary workaround is adding ${PODS_ROOT}/*\* to USER HEADER SEARCH PATHS in the OneDriveSDK build settings and turning on Always Search User Header Search Paths.

**Comment by kevklam** [comment]
Should be fixed now.
