### ISSUE TITLE
Update ADAL

### ISSUE THREAD

**Issue by chaseholland** [OneDrive/onedrive-sdk-ios#124]
ADAL is v1.x and ADAL is now on v2.

**Comment by Alex-C-Eltima** [comment]
Hi, is there any estimated time when ADAL is going to be updated in this SDK?

**Comment by Aravindmariappan** [comment]
Hello,

ADAL v1.x is not supported in iOS 11. Please update it for onedrive iOS 11 support.

Thanks

**Comment by ramonpoca** [comment]
Build fails in XCode 9b4 due to (very) old ADAL, is there anyone listening?

```
 /* com.apple.ibtool.document.warnings */
 /Users/ramon/Desktop/Projects/CloudGallery/FileManager/FileManager/Pods/ADALiOS/ADALiOS/ADALiOS/ADAL_iPad_Storyboard.storyboard:global: warning: This file is set to build for a version older than the deployment target. Functionality may be limited. [9]
/* com.apple.ibtool.document.errors */
/Users/ramon/Desktop/Projects/CloudGallery/FileManager/FileManager/Pods/ADALiOS/ADALiOS/ADALiOS/ADAL_iPad_Storyboard.storyboard:global: error: Compiling IB documents for earlier than iOS 7 is no longer supported. [12]
```

**Comment by chaseholland** [comment]
I'm going to push harder on this... I'm now seeing the same in xcode 9b4

**Comment by chaseholland** [comment]
I examined how much work it was to move to ADALv2... I've decided to patch ADALiOS v1.2.9 with the necessary changes to make it compile in Xcode 9b4.

As soon as I can get approval, I'll open a CR to this pod to use it CR here: https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/1028

**Comment by xinatanil** [comment]
I still can't compile my project on Xcode 9 Beta because of ADALiOS, and considering that Xcode GM and iOS 11 will be released within a couple of weeks, I'd say that this issue becomes critical.

**Comment by kevklam** [comment]
Just an update on this, Chase's PR has been merged by ADAL but they are waiting to validate against the GM before pushing a pod update.

**Comment by ghost** [comment]
The GM of Xcode 9 is released, when we get the solution with in pod update ?

**Comment by ramonpoca** [comment]
The ADALiOS repo is missing the tag for 1.2.9.1 and a push of the podspec.

**Comment by AndreasBoehm** [comment]
Please create the tag 1.2.9.1 and push to the podspec to allow us to upgrade to xcode 9

**Comment by ramonpoca** [comment]
ADALiOS has pushed 1.2.10 with the fixes (renamed package to ADAL). Podspec should pin to that version.

**Comment by ramonpoca** [comment]
@chaseholland Any estimate when you can push this?

**Comment by kevklam** [comment]
This has been pushed with #184 and the latest pod version. Please let me know if you continue to see issues.
