### ISSUE TITLE
App keep refreshing account session if the current account session is expired

### ISSUE THREAD

**Issue by gigades** [OneDrive/onedrive-sdk-ios#125]
It seems [ODAccountStore storeAccount] does not assign new session to the currentAccountSession variable when it is called by [ODBaseAuthProvider refreshAndStoreAccountSession] so the expired session will keep being checked instead of the new one.

**Comment by kevklam** [comment]
Thanks, I've merged your PR.

I'm a bit curious about how you have your client/auth provider set up. Are you creating a new client/authprovider for every request? It looks to me like there shouldn't be a problem in the typical case where the client/authprovider is created once and kept around until the user signs out - The check [ODBaseAuthProvider shouldRefreshSession:] looks at self.accountSession, which should get updated in refreshAndStoreAccountSession.

**Comment by gigades** [comment]
Thank you for accepting PR.

Your assumption is correct. My app lets users schedule downloading jobs from many kinds of cloud storages (Google Drive, OneDrive, Dropbox, etc.) so I design the app to dispose resources related with that job after it is finished and recreate it when necessary.
