### ISSUE TITLE
ODURLSessionDownloadTask.progress is 'nil' after calling [ODItemContentRequest downloadWithCompletion]

### ISSUE THREAD

**Issue by gigades** [OneDrive/onedrive-sdk-ios#126]
In case of current account session need refreshing, after calling [ODItemContentRequest downloadWithCompletion], the value of [ODURLSessionDownloadTask.progress] will still be 'nil' until account session has been refreshed so there is no way to add observer to the progress property.

**Comment by kevklam** [comment]
Should be fixed now, thanks for reporting/investigating!
