### ISSUE TITLE
user_id/authentication_token?

### ISSUE THREAD

**Issue by wang2nd** [OneDrive/onedrive-sdk-ios#127]
If using Microsoft Personal Account to sign in from a Mobile App through the windows live authentication,
within the token response we get, there is not any authentication_code according to Windows Live OAuth2 Response Parameters definition(https://msdn.microsoft.com/en-us/library/hh243647.aspx#response), instead we got the user_id, it is not a JWT token, the value is something like "AAAAAAAAAAAAAAAAAAAAAF82T9eFNt4sYYyv7hxFtNQ". The access_token itself is not a JWT token either. 

If using Microsoft Work Account to sign in as a Mobile App through the Azure AD authentication, within the token response we get, it contains an id_token, which is a JWT token but not signed. But gladly the access_token itself is a signed JWT token so that we can verify it is issued by Microsoft and trust the identity. 

The accountSessionWithResponse code(especially the comments '// Active Directory obfuscates the id and calls it id_token') in ODAuthHelper.m confirms the observations based on testing.

In General, we need a workaround for using Microsoft Personal Account to sign in from a Mobile App case, which can give us a signed token so that we can verify that it is signed by Microsoft and trust the info contained in the token and be able to link that info back to an actual user profile.

For Microsoft Work or School Account, no matter MobileApp or Web App, we rely on access_token and id_token.
For Microsoft Personal Account from Web App, we have the authentication_code, but for Mobile App, we need some guidance to take advantage of this user_id or some kind of signed token. Any link or hints?

Thanks,

**Comment by kevklam** [comment]
When using Microsoft Account authentication, the user_id is an opaque string uniquely identifying the user. The access_token is an opaque token appended to requests made to the service for authorization. Neither of these should be interpreted by the application other than as described, as their formats are not documented or guaranteed to remain the same.

It sounds like you are asking about OpenID functionality where the access token format is documented and can be parsed to get user profile information. I do not believe that is currently supported by the Microsoft Account OAuth endpoint. The [Microsoft Graph SDK](https://github.com/microsoftgraph/msgraph-sdk-ios) authenticates against the v2.0 Authentication Endpoint which supports a subset of OpenID when 'openid' scope is requested during authentication, and may provide the functionality you want.

Regarding token signing, I'm not sure I understand what the trust issue is - if you just want to map the authentication result to a user profile, you should be able to use the user_id as a string key uniquely identifying the user. Since the authentication flow happens over SSL, this string should be trustworthy unless the trust chain has already been compromised.

**Comment by wang2nd** [comment]
Thanks a lot Kevin for the reply! Yes, we are trying to looking for the OpenID idtoken equivalent in the Microsoft Account Authentication. 
- For AzureAD Authorization, it has been already supported even if in the v1.0 authentication endpoints described in https://login.microsoftonline.com/common/.well-known/openid-configuration; 
- For Microsoft Account Authentication on Web Application, in fact for our own Web Application Client that utilizes the Authorization Code Flow, with the Client ID & Secret configured, we have the authentication_token back, which is a jwt token and we treat it as an id_token equivalent.

The only exception is for Microsoft Account Authentication on a Mobile Application. The access token returned is correct, which I can use to fetch my own user profile on https://apis.live.net/v5.0/me and my global id. The global "id" returned here is not opaque and totally different with the user_id returned in the access token response, which is opaque as you mentioned and i don't think we can actually use it to link back to this user on other applications. e.g. when you want to specify the user id of a user for API https://apis.live.net/v5.0/{user_id}, you have to specify the global "id" returned by user profile, not the user_id embedded in the access token response.  Any example that how can we use this user_id? I assume it is only unique to this registered client.

The purpose that why we want to find the id_token equivalent is that: We tried to get the idToken equivalent on the mobile side through your SDK and pass it to our backend server to identify this user against Microsoft. Or else, we have to implement this Mobile App as a browser agent, and our backend server as the Web App client of the Microsoft Account Authorization Server. Although we have already implemented this for our actual web client, for our mobile client, we tried to take advantage of your SDK and not only authenticate the signed in user in this mobile application itself but also on the backend server.(one stone two birds, not two stones:)) 
Note: since the flow we want includes three parties, Microsoft, Mobile App, and a backend server, the backend server should only trust an id token signed by Microsoft, we can not pass the Microsoft access token to the backend server in this architecture. It is insecure.

We'd love to upgrade to V2 so that we don't need to maintain Microsoft and AZureAD authentication separately and it comply the OpenID standard more formally. But before it is fully GA, we have to stay at v1 for our production. Any rough estimation when the V2 will be fully GA and when the ADAL SDK for V2 will be available? If it is not far, maybe we can wait as you suggested.

**Comment by wang2nd** [comment]
Another interesting update. For the Microsoft client (client id **0000000048160AF8**) used by the iOSExplorer example, I can not get Authentication Token even if with the raw HTTP API instead of the the library;  But from the Microsoft client (client id **000000004C146A60**) used by One Drive SDK for Android example, I can get the Authentication Token back. 

It looks like the root cause is on the Client Registration and Configuration and has nothing to do with the client library or the OAuth APIs calls.  The client I registered (An Mobile App in https://apps.dev.microsoft.com/#/appList) behave same as the iOS example client. There is not too much to toggle.

If it is possible, a side by side comparison of the iOS client 0000000048160AF8 and Android client 000000004C146A60 configuration might reveal the secret.

**Comment by wang2nd** [comment]
Last update, in fact if we request the openid scope together with other scopes, we will get the ID token back as v2, even with your library, although the library does not expose it in the AccountSession class. You can expose this since the live api backend has already support v2. I really hope you can expose it so that I don't need to keep the changes in my local or my forked repo and just use your library directly.

For the MSGraph SDK, there is an msgraph-sdk-ios-nxoauth2-adapter to use, but it does not work well with my Swift codes, no matter with or without bridge header. 

Following are the calls I used fyi.
https://login.live.com/oauth20_authorize.srf?client_id=0000000048160AF8&redirect_uri=https://login.live.com/oauth20_desktop.srf&scope=openid%20wl.emails%20wl.basic&response_type=code
https://login.live.com/oauth20_token.srf?client_id=0000000048160AF8&redirect_uri=https://login.live.com/oauth20_desktop.srf&grant_type=authorization_code&code=M0de53dab-534b-3001-a976-fe612884288a

here is the response I get from your sample client 
{
  "token_type": "bearer",
  "expires_in": 3600,
  "scope": "wl.emails wl.basic onedrive.readwrite",
  "access_token": "EwD4A... TGpRhvhDwIABcNpca10CVfrAQ==",
  "id_token": "ey....jsH8A"
}

This will fulfill my requirement. Please forget about the Authentication_Token since it doesn't contain email at all.  

But I guess the final endpoint of Microsoft Personal Account v2 will not be live endpoint https://login.live.com/oauth20_authorize.srf but the https://login.microsoftonline.com/common/oauth2/v2.0/authorize shared together with work and school account/

**Comment by wang2nd** [comment]
Last update, in fact if we request the openid scope together with other scopes, we will get the ID token back as v2, even with your library. The actual accountId returned here will be the id_token, just like Microsoft work account for One Drive for Business. So everything looks fine.

For the MSGraph SDK, there is an msgraph-sdk-ios-nxoauth2-adapter to use, but it does not work well with my Swift codes, no matter with or without bridge header.

Following are the calls I used fyi.
https://login.live.com/oauth20_authorize.srf?client_id=0000000048160AF8&redirect_uri=https://login.live.com/oauth20_desktop.srf&scope=openid%20wl.emails%20wl.basic&response_type=code
https://login.live.com/oauth20_token.srf?client_id=0000000048160AF8&redirect_uri=https://login.live.com/oauth20_desktop.srf&grant_type=authorization_code&code=M0de53dab-534b-3001-a976-fe612884288a

here is the response I get from your sample client
{
"token_type": "bearer",
"expires_in": 3600,
"scope": "wl.emails wl.basic onedrive.readwrite",
"access_token": "EwD4A... TGpRhvhDwIABcNpca10CVfrAQ==",
"id_token": "ey....jsH8A"
}

This will fulfill my requirement. Please forget about the Authentication_Token since it doesn't contain email at all.

But I guess the final endpoint of Microsoft Personal Account v2 will not be live endpoint https://login.live.com/oauth20_authorize.srf but the https://login.microsoftonline.com/common/oauth2/v2.0/authorize shared together with work and school account/

**Comment by wang2nd** [comment]
This issue can be closed since the the accountId in the AccountSession object for Microsoft Personal Account will stand for 
- user_id if you dont request the openid scope
- id_token if you request the openid scope
