### ISSUE TITLE
The accessToken expired time get from sdks is too short

### ISSUE THREAD

**Issue by slunlun** [OneDrive/onedrive-sdk-ios#138]
Hi, I am writing APP about OneDrive, and store the account session on local disk. I notice that the account session get from SDK do not have refresh token, so I can only use the access token for very short time. 
Is there anyway to get account session with refresh token by iOS SDK?

**Comment by kevklam** [comment]
You'll need to include the 'offline_access' scope when setting up your ODClient:

[ODClient setMicrosoftAccountAppId:@"{id}" scopes:@[@"onedrive.readwrite,**offline_access**"]]
