### ISSUE TITLE
(Swift) Could not build module 'ADALiOS' when installing from Cocoapods with use_framworks!

### ISSUE THREAD

**Issue by nalexander50** [OneDrive/onedrive-sdk-ios#139]
I am trying to use a Swift framework alongside OneDriveSDK in my new Swift project. After adding the `use_frameworks!` flag in my Podfile and installing, my build fails. The first error is that the module ADALiOS could not be built. The highlighted line is 

`#import "ADUserInformation.h"`

Secondly, `ADPersistentTokenCacheStore.h` also fails to build. There are a number of cryptic error messages such as expected parameter declarator.

I have a Bridging Header importing OneDriveSDK.h. If I use Cocapods without `use_frameworks!`, everything works just fine. I am able to fully use the OneDriveSDK.

This is a huge issue since OneDriveSDK is basically forcing me to use either Objective-C libraries or Swift libraries, but not both.

**Comment by marekmatula** [comment]
I use the same configuration. It works fine.
Xcode version: 8.2.
Pod versions:
ADALiOS (1.2.9)
CRMMobileSDK (1.0.0)

I use only use_frameworks! and no bridging header.
App is connected to sharepoint site and can list main document library.
