### ISSUE TITLE
How to get user details?

### ISSUE THREAD

**Issue by vinceplusplus** [OneDrive/onedrive-sdk-ios#143]
There was a similar issue, #5, a year ago. Any update on API and SDK? Thanks

**Comment by rgregg** [comment]
@vinceplusplus:

This information is now available via [Microsoft Graph](https://graph.microsoft.com). You can either continue to use OneDrive API and only call Microsoft Graph for user information, or migrate to Microsoft Graph for the full scenario, since the OneDrive API is also available as part of the Microsoft Graph.

-Ryan

**Comment by deco1515** [comment]
@rgregg, I still failed to get displayname with the example project "IOSExplorer". Any suggestion?

**Comment by MintSet** [comment]
Can I use MSGraph with access token getting from OneDriveSDK?

**Comment by MintSet** [comment]
@deco1515, I spent a lot of time to solve this problem. I forked this repo and add to ODClient user email. [https://github.com/MintSet/onedrive-sdk-ios](url)

**Comment by kevklam** [comment]
@deco1515 
Information on using the MSGraph API to retrieve user info is documented here:
https://graph.microsoft.io/en-us/docs/api-reference/v1.0/resources/users
https://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/user_get

You can experiment directly with the API here:
https://graph.microsoft.io/en-us/graph-explorer

Once you know what API requests you need, you can use the MSGraph SDK to construct/execute the requests in your app:
https://github.com/microsoftgraph/msgraph-sdk-ios

If you need further assistance, please open an issue in the MSGraph SDK repo for greater visibility and @ mention me.

Thanks,
Kevin

**Comment by bazik123** [comment]
@kevklam is there a way to authenticate in MSGraph SDK once I am authenticated in OneDrive SDK? MSGraph github page is telling me it's not production ready so I am not thrilled at the prospect of migrating to it completely..
