### ISSUE TITLE
Share OneDrive folder?

### ISSUE THREAD

**Issue by kjoneandrei** [OneDrive/onedrive-sdk-ios#145]
How is it possible to generate a link to share an folder? Same as you can do on the one drive web version where you can generate a link and then the receiver by opening it can add it to his own drive as well ?

**Comment by kevklam** [comment]
The 'createLink' API should do what you want: https://dev.onedrive.com/items/sharing_createLink.htm

**Comment by kjoneandrei** [comment]
hei @kevklam ... i tried what you said above and it didn't really work: 
here is some of my code

```
   var url = "https://onedrive.live.com/drive/items/\(itemId)/action.createLink"

        url = url.stringByAddingPercentEscapesUsingEncoding(NSUTF8StringEncoding)!
        print()

        let request = NSMutableURLRequest(URL: NSURL(string: url)!)
        request.HTTPMethod = "POST"
```

any other variation of the url that i could think was rejected

**Comment by kevklam** [comment]
Sorry, I referred to the above link just to point out the relevant API. You'll need to access this API through the SDK in order to handle authentication. First go through the steps in 'Installation' and 'Getting Started' in the README for this repo, and then you will be able to access the createLink API as such:

``` objc
[[[[[[self.odClient drive] items:@"root"] itemByPath:@"path/to/item.doc"] createLinkWithType:@"view"]
    request] executeWithCompletion:^(ODPermission *response, NSError *error) {
    NSLog(@"Share link: %@", response.link.webUrl);
}];
```

**Comment by kjoneandrei** [comment]
hei @kevklam ... thanks a lot :P
