### ISSUE TITLE
Get data of custom columns and taxkeyword and also filter based on them.

### ISSUE THREAD

**Issue by rashikraj** [OneDrive/onedrive-sdk-ios#148]
Hi,

Is it possible to use the api to search/filter based on custom columns and also Enterprise keyword(Taxkeyword)? Also retrieve those custom column data?

If it is possible could you please provide a sample snippet.

Thanks.

**Comment by kevklam** [comment]
Hi,
Unfortunately the API does not currently support custom columns.

Thanks,
Kevin
