### ISSUE TITLE
Cancel button does nothing

### ISSUE THREAD

**Issue by mobilekosmos** [OneDrive/onedrive-sdk-ios#149]
All the functionality of OneDrive is working correctly, only the cancel button in the left upper corner when trying to login does not work, and this is automatically managed by the SDK, right?
I call following:
` [ODClient authenticatedClientWithCompletion:^(ODClient *client, NSError *error){`

this calls the first page where the user must input the mail address, on this first page the cancel button works, but on the next ones, for the password and for accepting permissions, pressing cancel does nothing. This cannot be a problem on my side, right? I tested the example app and the cancel button did work on it, so I am confused why it wouldn't work in my app, do you have any ideas?

**Comment by kreuli** [comment]
Issue seems to be in "ODAuthenticationViewController.m", in "shouldStartLoadWithRequest": when a request has the same prefix as "endURL", the property "isComplete" is set to YES. The "cancel" method ignores to cancel when "isComplete" is set.

Unfortunately I cannot suggest a fix since I don't know what the idea behind "isComplete" and "endURL" is, there are almost no comments in this module :-(.

**Comment by kevklam** [comment]
Thanks for reporting this, and my apologies for the slow response.

I believe the faulty logic is [ODAuthenticationViewController redirectWithStartUrl: ...], which does not reset isComplete as it should. I will submit a PR to fix it.

For more background on what isComplete and endURL are for, the OAuth 2.0 protocol specifies that the auth server will redirect to the 'redirect url' when the user completes login, passing an extra query param for the auth code. The 'endURL' logic is detecting when this final redirect occurs and extracting the auth code from it. 'isComplete' is just there to prevent an issue where you could accidentally cancel multiple times, or cancel at the same time as the auth flow is completing and returning a success result, which could cause problems for the application.

I believe the specific issue here is that the auth VC used in the discovery flow (when app is configured for both AAD and MSA auth) is reused for the OAuth flow after discovery completes by calling redirectWithStartUrl, which does not reset the isComplete flag.
