### ISSUE TITLE
oneDriveAccountStore.plist in Documents folder

### ISSUE THREAD

**Issue by vincenttsai** [OneDrive/onedrive-sdk-ios#15]
Hello I found there is a file oneDriveAccountStore.plist in documents folder once login. This maybe cause some issues. Some document based app may open this folder to users so they can download files in Documents folder from iTunes.  User can also choice to delete files via iTunes. And in my app, I will list all the files under documents for user to operate and I have to filter out these files now.  It would be better to put the onedrive relatived files under cache folder.

Thanks

**Comment by vincenttsai** [comment]
BTW, there are some other random files appear in the Documents as well. These files will show up very shortly looks like some temp file.

![random](https://cloud.githubusercontent.com/assets/1673319/9953125/697fb32c-5e10-11e5-9724-d9a335beb3f7.jpg)

Thanks

**Comment by aclev** [comment]
Hi @vincenttsai I will look into moving the default file location.  For now if you wish to change the location you can do so by creating you own `ODAccountStore` with the `[[ODAccountStore alloc] initWithStoreLocation:@"path/to/plist"]`  You can then set the default account store with `[ODClient setAccountStore:accountStore]` .  If you do this you must set the account store before you try and load any accounts or authenticate a client.  You should call the method right after you set your application id and scopes.  Also note that it wont migrate the account store for you and you will have to load the accounts again.

**Comment by vincenttsai** [comment]
@aclev It works as charm. Thanks for your help. BTW, I really love this SDK then LiveSDK. It's all block based and reduce a lot of code to achieve the same function. I spend a lot time to refactor from LiveSDK and I think it's worth. Thanks for your effort.

**Comment by aclev** [comment]
Thanks @vincenttsai!
