### ISSUE TITLE
Authentication failure issue.

### ISSUE THREAD

**Issue by gouravnayyar** [OneDrive/onedrive-sdk-ios#150]
I am not able to by pass the authentication step. My application is targeting OneDrive for Business. This is how my call looks like, (as mentioned in the doc)

[ODClient setActiveDirectoryAppId:"ONE_DRIVE_BUSINESS_CLIENT_ID" redirectURL:@"REDIRECT_URI"]];

I keep on getting the authentication issue. 

Question thread: 
http://stackoverflow.com/questions/41140326/authentication-issue-on-integrating-onedrive-ios-sdk

Any lead would be much appreciated. Thanks.

**Comment by kevklam** [comment]
Hi @gouravnayyar, are you still having this issue?
Have you tried running the iOSExplorer sample app in this repo (but replacing the app ID and redirect URI in ODXAppDelegate.m with your own)?

**Comment by gouravnayyar** [comment]
@kevklam Thanks for replying. 

Yes I have tried in the sample app after replacing the app ID and redirect URI. I am not able to pass the authentication step mentioned above.

**Comment by tobihagemann** [comment]
@gouravnayyar Were you able to solve this issue? I've just started looking into OneDrive for Business and I'm having the exact same error.

```
The application '…' required resource access list does not contain applications discoverable by 'https://api.office.com/discovery/'.
```

What does that even mean? :laughing:

Update: ~I think I've figured it out.~ Okay, not really. This is ridiculous. See #170.
