### ISSUE TITLE
fail to get user display name

### ISSUE THREAD

**Issue by deco1515** [OneDrive/onedrive-sdk-ios#152]
`ODClient.setMicrosoftAccountAppId("d808e948-8e94-4227-b5ec-a19222d7187b", scopes: ["wl.signin", "wl.offline_access", "onedrive.readonly", "onedrive.readwrite", "onedrive.appfolder"]) ODClient.authenticatedClient(completion: {client, error in if error == nil{ client?.drive().request().getWithCompletion({drive, error in print("---\(drive?.owner.user.displayName)") }) }`

I use the code above with SWIFT, and the result is NIL.
I have tested the example iOSExplorer, and get the same result.

**Comment by kevklam** [comment]
Please file an issue here instead:
https://github.com/OneDrive/onedrive-api-docs/issues
