### ISSUE TITLE
Unable to upload image from OneDrive IOS SDK

### ISSUE THREAD

**Issue by khaleel8039** [OneDrive/onedrive-sdk-ios#154]
Below is the piece of code i am using for image uploading:

NSURL *fileURL = [[NSBundle mainBundle] URLForResource:@"demoImage" withExtension:@"jpeg"];
ODItemContentRequest *request = [[[self.client drive] items:destDir] contentRequest];
[request uploadFromFile:fileURL completion:^(ODItem *item, NSError *error){
}];

Getting the following error while uploading image:

**OneDrive SDK ERROR : Error from download response Error Domain=com.microsoft.onedrive.errors Code=405 "method not allowed" UserInfo={error= invalidRequest : Item does not match expected type, NSLocalizedDescription=method not allowed}**

**Comment by kevklam** [comment]
You are requesting to modify the binary contents of the folder itself, instead of trying to upload contents to a new file.

NSString *fileName = "fileToCreate.txt";
[[[[[self.client drive] items:destDir] **itemByPath:fileName]** contentRequest] uploadFromFile:fileURL completion: ...];

**Comment by khaleel8039** [comment]
Its working now thanks a lot kevklam.
