### ISSUE TITLE
Accessing Sharepoint Sites

### ISSUE THREAD

**Issue by shammatime** [OneDrive/onedrive-sdk-ios#157]
I am trying to integrate with onedrive for business. Based on the documentation I am unsure of how to utilize the SDK to access sharepoint sites. Any help would be appreciated.

**Comment by kevklam** [comment]
It depends on what your needs are. Are you trying to access arbitrary sharepoint sites, or just the user's onedrive-for-business (i.e. their My Site)?

**Comment by shammatime** [comment]
@kevklam The example of what we are tying to access is:
Say I log into my one drive for business account. On the left hand side there is a listing for "Groups". I believe these are also considered "Sites" in sharepoint. Basically we are trying to figure out how to access these sites/groups using the onedrive sdk.

**Comment by kevklam** [comment]
Unfortunately this functionality is not currently supported in the OneDrive for Business API.

There exists a beta in the Microsoft Graph API that may help with what you are trying to do, however it is not production-quality yet:
https://graph.microsoft.io/en-us/docs/api-reference/beta/resources/sharepoint

The corresponding SDK is here:
https://github.com/microsoftgraph/msgraph-sdk-ios
