### ISSUE TITLE
Generate shared link to file

### ISSUE THREAD

**Issue by ghost** [OneDrive/onedrive-sdk-ios#16]
How would one go about generating a shared link to an uploaded file? A link that does not expire and can be opened by other people

**Comment by aclev** [comment]
Hi @manikkalra Thanks for the question!
Here is the documentation for our [sharing links](https://dev.onedrive.com/items/sharing_createLink.htm)
In the SDK this will look like other actions on items :

```
[[[[[client drive] items:@"itemId"] createLinkWithType:@"view"] request] executeWithCompletion:(ODPermission *permission, NSError *error){
// permission.link.webUrl contains the url
}];
```

**Comment by ghost** [comment]
Thank you for your response! Will this link be public? If not, can I make it public?

**Comment by aclev** [comment]
What are you trying to accomplish with the link?  The webURL is the url to access the file within the browser, anyone with the link can access it.

**Comment by ghost** [comment]
I want to make sure other people can view it without having to log into OneDrive. Is that what you meant?

**Comment by aclev** [comment]
Yes, this link will work for anybody (you do not need to be logged in)

**Comment by ghost** [comment]
Thank you :)
