### ISSUE TITLE
In Swift

### ISSUE THREAD

**Issue by MirAshrafUddin** [OneDrive/onedrive-sdk-ios#163]
I want to make a project using onedrive api in swift. how can I do that? please give me some suggestions...

**Comment by MirAshrafUddin** [comment]
I solved it using this project https://github.com/microsoftgraph/ios-swift-snippets-sample

**Comment by sreejithsree123** [comment]
@MirAshrafUddin you Know how to show the progress bar for uploading and downloading in swift. sorry for asking here because no one is responding for my question. :)
