### ISSUE TITLE
how to rebuild ODClient with token

### ISSUE THREAD

**Issue by deco1515** [OneDrive/onedrive-sdk-ios#165]
I got ODClient by calling `ODClient.authenticatedClient`.
Now I want to rebuild ODClient in another device.
what can I do?

**Comment by kevklam** [comment]
Unfortunately that isn't currently a supported scenario. It should be possible by writing your own ODAuthProvider or likely by subclassing an existing one, however there is a lot of convenience logic that is coded to specifically work with the existing auth providers that won't be usable (i.e. most of the stuff in ODClient+Authentication and ODClient+DefaultConfiguration).
