### ISSUE TITLE
Access and fetch items from a public shared folder with no authenicated client

### ISSUE THREAD

**Issue by ozzotto** [OneDrive/onedrive-sdk-ios#166]
Is there a way to use the iOS SDK and fetch and access (read-only) the items of a public shared folder - [example](https://onedrive.live.com/?authkey=%21AOtB3GLnhmonfq4&id=98FEE311F7E754ED%213928&cid=98FEE311F7E754ED) - without having to authenticate the ODClient?

**Comment by kevklam** [comment]
The API does not seem to support this. If it did, you would do so using the /shares/ API:
https://dev.onedrive.com/shares/shares.htm
