### ISSUE TITLE
what is the query that returns all items (so they can be filtered with fields like 'folder <> null && lastModifiedDate < now-3'

### ISSUE THREAD

**Issue by bazik123** [OneDrive/onedrive-sdk-ios#168]
i would like to search onedrive using the filtering query format (all non deleted folders modified in last 3 days), and from what I gather I can only get this by filtering after I search.

so my question: what query returns ALL items (so I can filter them using folder/delelted/modifiedDate? 

I tried "" and "*", I tried bypassing search by having a query like "folder ne null"

**Comment by kevklam** [comment]
You can use the 'delta' API to pull down all items in a hierarchy. Please see API reference here:
https://dev.onedrive.com/items/view_delta.htm

The search API you're trying to use is primarily a keyword search.

Thanks
