### ISSUE TITLE
OneDrive for Business `cTag` not updated when folder contents changes

### ISSUE THREAD

**Issue by azubala** [OneDrive/onedrive-sdk-ios#171]
Steps to reproduce:
-  create a folder in OD for Business
- add some files to the folder
- in iOS application using OD iOS SDK fetch folder and print out `cTag` property
- change folder contents by adding or deleting or modifying files
- re-run the application

Result:
- `cTag` property of the folder is the same

Expected behaviour:
- `cTag` property should reflect changes of folder contents; as stated in docs (https://dev.onedrive.com/resources/item.htm) :

> Note: The eTag and cTag properties work differently on containers (folders). The cTag value is modified when content or metadata of any descendant of the folder is changed. The eTag value is only modified when the folder's properties are changed, except for properties that are derived from descendants (like childCount or lastModifiedDateTime).

Please note that the expected behaviour is working properly when using OneDrive personal.

**Comment by kevklam** [comment]
Hi, please refer this API issue to [onedrive-api-docs](https://github.com/OneDrive/onedrive-api-docs/issues) and if possible include details of the specific HTTP requests being made.

Thanks.
