### ISSUE TITLE
searchWithQ not working in Obj-C

### ISSUE THREAD

**Issue by kennybuc** [OneDrive/onedrive-sdk-ios#174]
I integrated OneDrive SDK for iOS to my Obj-C project. Everything seems working fine but search function.

[[self.odClient.root searchWithQ:@".privacy.txt"] request]

The search function does not work immediately after I uploaded a file, ".privacy.txt".
It then works after few mins. And sometimes search response is empty array but this rarely happens.

If anybody has experienced this kind of issue, please help me.

Thanks!

**Comment by kennybuc** [comment]
@kevklam Did you have got a chance to reproduce the same issue?

**Comment by kevklam** [comment]
Hi,
The search function relies on a server side index that gets populated asynchronously, so there is some delay between files being uploaded and being searchable.


________________________________
