### ISSUE TITLE
OneDrive for business - create file fails(UnauthorizedAccessException) for AppOnly accessToken

### ISSUE THREAD

**Issue by lockelost** [OneDrive/onedrive-sdk-ios#175]
Hi,
this is not specifically related with the C# SDK, but rather it is about the server side implementation, I guess.

I got the Access token by using following method.
https://developer.microsoft.com/en-us/graph/docs/concepts/auth_v2_service

By calling the Micorosoft Graph API, I can list up files of every user in tenant, download them, and even can create a folder. 
but I can not create file, the response is 
"{\"error\":{\"code\":\"-2147024891, System.UnauthorizedAccessException\",\"message\":\"Access denied. You do not have permission to perform this action or access this resource.\"}}"

The Azure app has all the permissions enabled, and If I get the AccessToken by going thru the Web Login based way, everything works (of course with some collection admin related configuration).

Microsoft Graph team's response imply that the actual function is depend on the OneDrive teams implementation.

Can you check on this?

Thanks in advance.

**Comment by kevklam** [comment]
Please open this issue in [onedrive-api-docs](https://github.com/onedrive/onedrive-api-docs/issues) for API related questions. It will also be helpful to include more details of the request you are making.

Thanks,
Kevin
