### ISSUE TITLE
does not build with ios 11

### ISSUE THREAD

**Issue by bazik123** [OneDrive/onedrive-sdk-ios#178]
related to: https://github.com/AzureAD/azure-activedirectory-library-for-objc/issues/1051

ADALios doesnt support ios 11, but onedrive-sdk-ios/Auth has an ADALios dependency

**Comment by kreuli** [comment]
Isn't this related to https://github.com/OneDrive/onedrive-sdk-ios/issues/124 ?

**Comment by ghost** [comment]
Yes it is. I have the same error from #124 with the Xcode 9 GM.

**Comment by sanhue0302** [comment]
i got same problem
please fix this problem, thanks

**Comment by j0sem4rio** [comment]
same problem

**Comment by sugampandey** [comment]
We see this problem too. Please fix

**Comment by kevklam** [comment]
Should be fixed with #184 and the latest pod version.
