### ISSUE TITLE
How to cancel the previous request ?

### ISSUE THREAD

**Issue by James24** [OneDrive/onedrive-sdk-ios#21]
[childrenRequests getWithCompletion:^(ODCollection *response, ODChildrenCollectionRequest *nextRequest, NSError *error){
        if (!error){
}
if(nextRequest)
{
 [self loadChildrenWithRequest:nextRequest];    //here
 }

if i have many files in a directory, nextRequest will call [self loadChildrenWithRequest:nextRequest] until we receive all the files. Before the iteration get complete, If i click some other directory, then previous directory files and currently clicked directory files are merged in result. Is there any way to cancel previous request @aclev

**Comment by aclev** [comment]
Hi @James24 When you call the `getWithCompletion` method this returns an `ODURLSessionDataTask` that contains a cancel method.

**Comment by James24** [comment]
Ya got it @aclev 

Working fine :+1:
