### ISSUE TITLE
Deprecated API Usage (UIWebView)

### ISSUE THREAD

**Issue by wang1925** [OneDrive/onedrive-sdk-ios#213]
Hi,

I've just tried to upload the new version of the app to App Store, but unfortunately I get a message from the Apple itself:

"Dear Developer,

We identified one or more issues with a recent delivery for your app. Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs starting from April 2020 . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

After you’ve corrected the issues, you can upload a new binary to App Store Connect.

Best regards,

The App Store Team"

This problem will affect submission of the app. Can you fix it？Looking forward to your reply.

All best!

**Comment by luisangelsm** [comment]
It looks to me that this sdk is deprecated, read this: https://github.com/OneDrive/onedrive-sdk-ios/issues/209

This issue is a blocker for whoever is using the sdk, I wonder if there is a migration guide to move from the onedrive sdk to Microsoft Graph SDK.

**Comment by OneSecure** [comment]
Since nobody want to do migrating, I do. My work looks fine. Maybe can help others.
Look https://github.com/OneSecure/onedrive-sdk-ios/commit/7a390f964ac1c893fb2ab4b80d05e3ed4388392c

I don't understand why Microsoft abandoned this SDK.

**Comment by wang1925** [comment]
> Since nobody want to do migrating, I do. My work looks fine. Maybe can help others.
> Look [OneSecure@7a390f9](https://github.com/OneSecure/onedrive-sdk-ios/commit/7a390f964ac1c893fb2ab4b80d05e3ed4388392c)
> 
> I don't understand why Microsoft abandoned this SDK.

Thans for your work，Great job

**Comment by kungfuslippers** [comment]
Hi OneSecure@7a390f9

I tried to get your UIWebView -> WKWebView changes by updating the reference to OneDriveSDK in my Podfile from :

pod 'OneDriveSDK', '1.3.0'
to:
pod 'OneDriveSDK', :git => 'https://github.com/OneSecure/onedrive-sdk-ios.git'

and all builds ok but I still get references to UIWebView in 

ADAuthenticationContext.h
ADAuthenticationViewController.h
ADAuthenticationViewController.m
ADAuthenticationWebViewController.h
ADAuthenticationWebViewController.m

I checked your commits and it seems as though you updated the files so unsure where the issue for me might be - any ideas?

**Comment by OneSecure** [comment]
I think you can NOT use pod command. You must use git clone instead.

**Comment by mdfalcon104** [comment]
@kungfuslippers  I got this error [!] Unable to find a specification for `ADAL (~> 1.2)` depended upon by `OneDriveSDK/Auth`.

Could you please give a hint?
