### ISSUE TITLE
Could not build module 'OneDriveSDK'

### ISSUE THREAD

**Issue by fmaia** [OneDrive/onedrive-sdk-ios#22]
Hi! I've installed the OneDriveSDK via cocoaPods using 'pod 'OneDriveSDK''.
However, i can't compile my project because it cannot build the OneDriveSDK.
The reason is that in the file: ODBusinessAuthProvider.h I get this error:

.../Pods/OneDriveSDK/OneDriveSDK/Auth/ODBusinessAuthProvider.h:23:9: 'ADAuthenticationContext.h' file not found

What should be the problem?

**Comment by aclev** [comment]
Hi @fmaia 
After you ran `pod install` did you open the .xcworkspace file it create instead of the .xcproj file?

**Comment by fmaia** [comment]
Hi @aclev! Thanks for your reply. 
Yes. I've been using pods without problems. But for the OneDriveSDK I'm having this issue. The strange thing is that if I go through the pods folder for ADALiOS, the file is actually there. I don't understand what pods is doing but something is missing...

Moreover, it only exhibits the error if I actually add
  #import OneDriveSDK/OneDriveSDK.h 

to my bridging file.

**Comment by aclev** [comment]
Hey @fmaia thanks reporting the bug!  I didn't realize you were using swift.  I was able to reproduce it locally and I think I may have fixed the issue. Can you try changing your podfile to   

```
pod 'OneDriveSDK', git : => https://github.com/aclev/onedrive-sdk-ios, branch : => 'swiftFix'
```

And see if that fixes the problem?  Also as a quick note cocoapods now has swift support, if you include `use_frameworks!` at the top of the Podfile you won't  need to include a bridging file (cocoapods will do all this work for you) just `import OneDriveSDK` wherever you need it.
Thanks!

**Comment by fmaia** [comment]
Thank you @aclev for the fix and the very useful hints! The project is now compiling without errors. 
btw this fix will be available in future versions of the API? in other words, are you able to estimate when may I use the main branch again?

**Comment by aclev** [comment]
Hi @fmaia Glad it works! Yes it will be available soon, i'll update this thread when I've checked it in.

**Comment by aclev** [comment]
Hey @fmaia  This is in master and in release 1.0.4
