### ISSUE TITLE
Xcode Archive Project Problem

### ISSUE THREAD

**Issue by tigernghk** [OneDrive/onedrive-sdk-ios#29]
I have added OneDriveSDK project to my app project. When I deploy my app to the device, it shows: 

dyld: Library not loaded: ...../OneDriveSDK
Reason: image not found

Then I need to add OneDriveSDK.framework to embedded libraries. This problem is solved.

However, it causes another issue: after archiving project, OneDriveSDK.framework is attached to my app. OneDriveSDK.framework is "explicitly" shown in the dialog when I tried to upload my app to app store. It supposed not to exist. 

Of course, remove OneDriveSDK.framework from embedded libraries, the problem will be solved. However, it returns to my first problem: I cannot deploy app to the device. 

Any solutions?

**Comment by aclev** [comment]
Hi @tigernghk I'm investigating the issue now.  Is there a reason you have included the embedded framework instead of using cocoapods?

**Comment by tigernghk** [comment]
I have executed 'pod install' under OneDriveSDK folder. 
And then I just drag and drop OneDriveSDK.xcodeproj to my app project.

Also, I need to remove "Copy Pods resources" in build phases of OneDriveSDK.xcodeproj. If not, XCode cannot generate iOS app archive (it generates xcode generic archive instead).

**Comment by aclev** [comment]
I strongly recommend you use cocoapods to include the OneDriveSDK in your project, this will make sure it is easy to update to newer versions and easier to manage the dependencies the SDK has itself.  It seems you have already installed cocoapods it is very easy to setup and include the OneDriveSDK.
All you need to do is navigate to your .xcproj file in a terminal and run `touch Podfile`.  Then open that file open and add

```
platform :ios, '8.0'
pod OneDriveSDK
```

or whatever version of iOS you support.  Then run `pod install` and open the .xcworkspace cocoapods created and you're done!

I am still investigating the original issue.

**Comment by tigernghk** [comment]
It works fine if using cocoapods. Thanks.
