### ISSUE TITLE
Login screen always pops up for live accounts

### ISSUE THREAD

**Issue by unpluggedk** [OneDrive/onedrive-sdk-ios#33]
Hi there, 
I am trying to create a simple app that does both live accounts and office accounts.
At the moment, when i log in using live accounts, it logs in but when i start the app, the information is not saved - thus new log in screen pops up every time.

This also happens in the included explorer. 

It seems like the pod pulls the older version of the ADALiOS, is this intended?

Thanks

**Comment by aclev** [comment]
Hi @unplugged, can you share how you are calling the login method? Can you also share what scopes you are using?

**Comment by unpluggedk** [comment]
sure,
I set the client info with 
    [ODClient setMicrosoftAccountAppId:@"XXXXXXX"
                                scopes:@[@"wl.signin",@"onedrive.readwrite", @"onedrive.appfolder"]];

and then use 
     [ODClient clientWithCompletion:^(ODClient *client, NSError *error){ ... 

to login.

**Comment by unpluggedk** [comment]
just to add, it signs me in and i am able to get drives, but it just asks me to sign on everytime i restart the app

**Comment by aclev** [comment]
For persistent access to a users onedrive you must specify the "wl.offline_access" scope.

**Comment by unpluggedk** [comment]
Got it, verified working
