### ISSUE TITLE
Error using Azure Active Directory

### ISSUE THREAD

**Issue by unpluggedk** [OneDrive/onedrive-sdk-ios#34]
When I use Azure Active Directory (with application permission to have all SharePoint Online permissions) and do
  [ODClient setActiveDirectoryAppId:@"XXXX" scopes:@[@"wl.signin",@"onedrive.readwrite", @"onedrive.appfolder"] redirectURL:@"https://specifiedredirect"];

it signs me in using Office 365 account, and the log in information is not required for each restart of the app. 
However, it fails in getting the drive with the following message

OneDrive SDK ERROR : Error from data task : Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSUnderlyingError=0x7fc1a2412740 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}, NSErrorFailingURLStringKey=_api/v2.0/me/drive/, NSErrorFailingURLKey=_api/v2.0/me/drive/, NSLocalizedDescription=unsupported URL}
2015-09-30 11:42:11.995 O365-iOS-CloudRoll[6331:144891] OneDrive SDK ERROR : Caused by request <NSMutableURLRequest: 0x7fc1a26c8cf0> { URL: _api/v2.0/me/drive/ }

is there something i am missing?
at first i thought there might be a different scopes string in the first place, but looking back at the log, is the URL valid?

thanks again!

**Comment by aclev** [comment]
Hi @unplugged, those scopes you are using are for Microsoft Account, try using "MyFiles.readwrite", It seems you have found a bug in some error handling, this doesn't seem like the right error message.
Thanks!

**Comment by unpluggedk** [comment]
Thanks! it works!

**Comment by unpluggedk** [comment]
Thanks it works, leaving it open as you've mentioned a error handling bug.
