### ISSUE TITLE
Unable to upload audio file

### ISSUE THREAD

**Issue by vincenttsai** [OneDrive/onedrive-sdk-ios#4]
I tried to upload an m4a or mp3 file with the following code.

NSURL *fileURL = xxxx;
ODItemContentRequest *request = [[[[ODClient loadCurrentClient] drive] items:path] contentRequest];
self.task = [request uploadFromFile:fileURL completion:^(ODItem *item, NSError *error) 

Then there is always return an error  "unsupported media type" UserInfo=0x7f7fb5172210 {error=  : The request entity's media type 'application/octet-stream' is not supported for this resource."

I know it probably the content type is wrong. But I have no idea how to fix this, since I have no way to get the NSMutableURLRequest created from your library.

Many thanks.

**Comment by aclev** [comment]
Hi @vincenttsai 
Thanks for your interest! Right now to append the content-type header to the contentRequest you can call: `[[[[ODClient loadCurrentClient] drive] items:path] contentRequestWithOptions:@[[[ODHeaderOptions alloc] initWithKey:@"Content-Type" Value:<type of content>]]]];`  

You can also append any headers or query parameters that way.  This seems like a common scenario and we can look into making this an easier call.

However, You shouldn't need to change the content-type from application/octet-stream for the upload to work. What is in the `path` variable, is that the path to the item? The items method takes the id of an item not the path.  If you want to access the items by their path you should call : `[[[[ODClient loadCurrentClient] root] itemByPath:path] contentRequest];`

**Comment by vincenttsai** [comment]
Hi @aclev 
Thanks for your nice code smell.
I tried to fix this with parentID and it turns out another error code 405(The HTTP method in the request is not allowed on the resource).  After I debug with the request, I found the URL was "https://api.onedrive.com/v1.0/drive/items/{parentID}/content" with put method. 
But in the document (https://dev.onedrive.com/items/upload_put.htm), there is no such url definition. So I change the variable itemID to format like
{parentID}:/{filename} , then i did get a /drive/items/{parent-id}:/{filename}:/content url with put method. Which seems match from document. 
Well, after I executed ,I still got another error Code=415 "unsupported media type,
 The request entity's media type 'application/octet-stream' is not supported for this resource.". Please guide me what should I do.

Here is my code
NSString *itemID = [NSString stringWithFormat:@"%@:/%@", parentID, [fileURL lastPathComponent]];
//NSString *itemID = parentID;
ODItemContentRequest *request = [[[[ODClient loadCurrentClient] drive] items:itemID] contentRequest];
self.task = [request uploadFromFile:fileURL completion:^(ODItem *item, NSError *error) ....

Another issue is from the document, the simple item put method can only support 100MB. Is there any api support for Resumable item upload?

Many thanks

**Comment by aclev** [comment]
Hi @vincenttsai 
We actually provided a way to access an item by path using the SDK if you see the [items](https://github.com/OneDrive/onedrive-sdk-ios/blob/master/docs/items.md) page.  You can do this via `[[[[odClient drive] items:parentId] itemByPath:@"path/to/file"] contentRequest]`  You are actually missing a colon at the end of your self constructed path.  This means you are trying to put to the metadata of a file named content at the location under the file you want to upload. We recommend using the itemByPath method to avoid this in the future.

Right now we have support to create an upload session and to retrieve the URL you need to upload the fragments.  We don't have support in the SDK to handle all of the fragment uploads just yet but it is on our radar. 

 You can see the [upload api](https://dev.onedrive.com/items/upload_large_files.htm) .   You can use the SDK to create an uploadSession via: `[[[[client drive] items:itemId] createSessionWithItem:chunkedUploadSessionDescriptor] request]`.  This will return a `ODUploadSession` with the URL you need to upload the fragments.

**Comment by vincenttsai** [comment]
Thanks, [[[[odClient drive] items:parentId] itemByPath:@"path/to/file"] works!
