### ISSUE TITLE
Storyboard missing in iOSExplorer!

### ISSUE THREAD

**Issue by santanu4ver** [OneDrive/onedrive-sdk-ios#45]
Xcode: 7.0.1

I'm having the following error when build:

/Users/shadow/Downloads/onedrive-sdk-ios-master/OneDriveSDK/Pods/ADALiOS/ADALiOS/ADALiOS/ADAL_iPad_Storyboard.storyboard: Interface Builder could not open the document ADAL_iPad_Storyboard.storyboard" because it does not exist.

I can see two .storyboard files are at Pods/ADALiOS/Resources, though. How should I fix this?

**Comment by rpassis** [comment]
Hi there it looks like you can safely remove those two files from the project as they have been replaced by a universal Main.storyboard which is included in the latest commit (under `Supporting Files/Base.lproj`).

I hope it helps.
Rog

**Comment by santanu4ver** [comment]
That worked! Thanks!
