### ISSUE TITLE
Get Progress without KVO

### ISSUE THREAD

**Issue by ghost** [OneDrive/onedrive-sdk-ios#47]
Is there anyway to get upload progress without KVO? I am getting weird behavior when the app stays in the background too long. I remove the observer before I deallocate, but that doesn't seem to help. Closing the app and reopening fixes that issue.

**Comment by aclev** [comment]
Hi @manikkalra the only way to get progress on an upload is with the NSProgress object on the upload task. Can you provide an example of how you are attaching the observer?  We can discuss other methods of obtaining progress for upload/download/async methods if you have suggestions.

**Comment by ghost** [comment]
This is how I am using it. The class I am using it is a shared instance. So, I needed to find a way to remove the observer without deallocating the class. Hence, I removed the observer right before I added it again (this method is called every-time I upload). Is there something I may be missing? 

```
 ODItemContentRequest *request = [[[[self.odClient drive] special:@"approot"] itemByPath:filename] contentRequest];
self.uploadTask = [request uploadFromData:jpegData completion:^(ODItem *item, NSError *error) {

                    [[[[[self.odClient drive] items:item.id] createLinkWithType:@"view"] request] executeWithCompletion:^(ODPermission *response, NSError *error) {

                            .........
                           NSString *sharedLink = response.link.webUrl;
                            dispatch_async(dispatch_get_main_queue(), ^{
                                success(sharedLink, item.id);
                            });
                    }];
            }];

            // Set up progress
            dispatch_async(dispatch_get_main_queue(), ^{

                [self removeObserver];
                [self.uploadTask.progress addObserver:self forKeyPath:NSStringFromSelector(@selector(fractionCompleted)) options:0 context:ProgressObserverContext];
            });
```

And here is how I remove the observer:

```
 -(void)removeObserver
{
    @try
    {
        [self.uploadTask.progress removeObserver:self forKeyPath:NSStringFromSelector(@selector(fractionCompleted)) context:ProgressObserverContext];
    }
    @catch (NSException * __unused exception) {}
}
```

**Comment by aclev** [comment]
Are you sure that the removeOberserver is getting called and not failing?  You are catching an exception and not doing anything with it.

**Comment by ghost** [comment]
If the observer is not yet set up, I expect it to fail. However, the removeObserver call will crash the app if not caught, and hence the empty catch statement.

**Comment by aclev** [comment]
You are calling removeOvserver before you have attached the observer.  You need to remove the observer after the upload is complete.

**Comment by ghost** [comment]
Here's what I am doing now. I'll test it a little more (KVO stops working after the app has been in the background for a while)

```
ODItemContentRequest *request = [[[[self.odClient drive] special:@"approot"] itemByPath:filename] contentRequest];
self.uploadTask = [request uploadFromData:jpegData completion:^(ODItem *item, NSError *error) {

                if (error)
                {
                    dispatch_async(dispatch_get_main_queue(), ^{

                        [self removeObserver];
                        err(error);
                    });
                }
                else
                {
                    dispatch_async(dispatch_get_main_queue(), ^{

                        [self removeObserver];
                        progress(1.0, YES);
                    });

                    [[[[[self.odClient drive] items:item.id] createLinkWithType:@"view"] request] executeWithCompletion:^(ODPermission *response, NSError *error) {

                        if(error)
                        {
                            dispatch_async(dispatch_get_main_queue(), ^{
                                err(error);
                            });
                        }
                        else
                        {
                            NSString *sharedLink = response.link.webUrl;
                            dispatch_async(dispatch_get_main_queue(), ^{
                                success(sharedLink, item.id);
                            });
                        }
                    }];
                }
            }];

            // Set up progress
            dispatch_async(dispatch_get_main_queue(), ^{

                [self.uploadTask.progress addObserver:self forKeyPath:NSStringFromSelector(@selector(fractionCompleted)) options:0 context:ProgressObserverContext];
            });
```

**Comment by ghost** [comment]
So after some testing, the progress does not work after the app has gone into the background a few times. Any advice for me?

**Comment by aclev** [comment]
I haven't been able to reproduce your issue here, Can you try setting self.uploadTask to nil after your remove the observer?

**Comment by ghost** [comment]
I will try that and let you know. Thank you!

**Comment by ghost** [comment]
I tired that but unfortunately it doesn't help :\

**Comment by kevklam** [comment]
Hi @manikkalra,
I am closing this issue as it has been inactive for a long time - please reopen if this needs further attention.
Thanks!
