### ISSUE TITLE
App folder children request returns empty array

### ISSUE THREAD

**Issue by rpassis** [OneDrive/onedrive-sdk-ios#48]
I'm using the iOS SDK to authenticate with a "onedrive.appfolder" scope and query/download files within the application folder.

The request below works as expected:

```
[[[[self.odClient drive] special:@"approot"] request] getWithCompletion:^(ODItem *response, NSError *error) {
  NSLog (@"response: %@", response);
}];
```

However when I modify it to fetch the children items instead, the response received is an empty array:

```
[[[[[self.odClient drive] special:@"approot"] children] request] getWithCompletion:^(ODCollection *response, ODChildrenCollectionRequest *nextRequest, NSError *error) {
  NSLog (@"response: %@", [response value]);
}];
```

If I try and fetch the items using an explicit path to the Apps folder, it works as expected and the array returned contains all 3 items within the app's folder.

```
[[[[[self.odClient root] itemByPath:@"Apps/[APP_NAME_REDACTED]"] children] request] getWithCompletion:^(ODCollection *response, ODChildrenCollectionRequest *nextRequest, NSError *error) {
    NSLog (@"response: %@", [response value]);
}
```

Is this a bug or am I doing something wrong?
Thanks,
Rog

**Comment by aclev** [comment]
Hi @rpassis This seems like a bug with the API, I'm investigating now.

**Comment by aclev** [comment]
Hey @rpassis I just realized that you have the wrong callback in your request.

```
[[[[[self.odClient drive] special:@"approot"] children] request] getWithCompletion:^(ODItem *response, NSError *error) {
  NSLog (@"response: %@", [response value]);
}];
```

Should be :

```
[[[[[self.odClient drive] special:@"approot"] children] request] getWithCompletion:^(ODCollection *children, ODChildrenCollectionRequest *nextRequest,  NSError *error) {
//Colleciton.value will be an array of items, it will be empty if there are no items in the folder.
}];
```

**Comment by rpassis** [comment]
Hi there

Thanks for investigating and apologies for confusing you by putting that code with the wrong callback. I am in fact using the correct one in code (otherwise the code wouldn't compile) and just modified the blocks above to illustrate my issue however forgot to replace it with the correct callback. I have done that now.

It looks like this is definitely a bug.

Rog

**Comment by rpassis** [comment]
To add more info to the above, here are the results of inspecting both the `NSHTTPURLResponse` and the JSON representation of the `NSData` received by the `NSURLSessionDataTask` (inside the SDK class `ODURLSessionDataTask`).

Based on the response received, it seems that this is a bug with the actual API and not the iOS SDK.

```
<NSHTTPURLResponse: 0x7fb6206a6af0> { URL: https://api.onedrive.com/v1.0/drive/special/approot/children } { status code: 200, headers {
    "Content-Encoding" = gzip;
    "Content-Length" = 119;
    "Content-Type" = "application/json; odata.metadata=minimal";
    Date = "Tue, 13 Oct 2015 23:17:05 GMT";
    "OData-Version" = "4.0";
    P3P = "CP=\"BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo\"";
    "Strict-Transport-Security" = "max-age=31536000; includeSubDomains";
    Via = "1.1 BN2SCH050480158 (wls-colorado)";
    "X-AsmVersion" = "UNKNOWN; 19.29.0.0";
    "X-MSEdge-Ref" = "Ref A: AF909DF8D75D473AB208AEEA2273A166 Ref B: B6051ACBA5AFE537BA244B29527F37CA Ref C: Tue Oct 13 16:17:05 2015 PST";
    "X-MSNSERVER" = "BN1301____PAP162";
    "X-WLSPROXY" = BN2SCH050480158;
} }
```

And the serialised JSON object:

```
{
    "@odata.context" = "https://api.onedrive.com/v1.0/$metadata#drives('me')/special('approot')/children";
    value =     (
    );
}
```

**Comment by aclev** [comment]
Are you positive that the app folder contains children?

**Comment by aclev** [comment]
You are right, there is a bug in the API.  We are working on a fix now.  I'll come notify you here when the bug is fixed.

**Comment by rpassis** [comment]
Looks like this might've been fixed. Are you able to confirm @aclev?
Thanks,
Rog

**Comment by aclev** [comment]
Hey @rpassis This has been fixed. Thanks for reporting the bug!
