### ISSUE TITLE
How to get email id from session or on login ? 

### ISSUE THREAD

**Issue by James24** [OneDrive/onedrive-sdk-ios#5]
I have logged in multiple accounts, It is difficult to identify the particular account with client.accountID, Is there any way to get email id for respective account id.

**Comment by rgregg** [comment]
There isn't -- yet. We're working on making this available from the API, which will then be available in the SDK.

**Comment by aclev** [comment]
Hi @James24 
For now you can get the name of the owner of a drive, to do this you can call :

```
[[[odClient drive] request] getWithCompletion:^(ODDrive *drive, NSError *error){
    if (!error){
        NSString *displayName = drive.owner.user.displayName;
   }
}
```

**Comment by James24** [comment]
ok thanku @rgregg  :+1:

**Comment by James24** [comment]
Superb. thanks a lot @aclev :+1:

**Comment by deco1515** [comment]
@aclev, I get empty displayName. but another property like 'token' 'id' is normal.
