### ISSUE TITLE
Item copying does not report progress and is holding completion handler indefinitely

### ISSUE THREAD

**Issue by vinceplusplus** [OneDrive/onedrive-sdk-ios#51]
According to the documentation of how to perform item copying, https://github.com/OneDrive/onedrive-sdk-ios/blob/master/docs/items.md, we should be able to monitor the progress property of the returned task. However, it reported either 0 or 1 when I was copying a folder with 3 files inside (a total of 4 items). status.percentageCompleted in the completion handler doesn't help too (either 0 or 1). status.status does report something verbally (like completed 2/4; x of y bytes)

Also as the title says, the completion handler is getting retained indefinitely thus it might be leaking memory

As the doc also says, the handler will be called whenever there is an update, is naming the method executeWithCompletion: misleading?

**Comment by aclev** [comment]
Hey @vinceplusplus Thanks for reporting the bug, I'm investigating now.

**Comment by aclev** [comment]
Hey @vinceplusplus, Thanks again for reporting the bug.  It seems that the monitor status api isn't updating the percentage correctly. This is a bug in the API and I will investigate further.  I have also found the memory leak in #58. It was related to what you said, but there was retain cycle with the data task that was created.  This is temporary fix for now.

**Comment by aclev** [comment]
fixed via #62
