### ISSUE TITLE
Copying/moving items across drives under the same user?

### ISSUE THREAD

**Issue by vinceplusplus** [OneDrive/onedrive-sdk-ios#53]
Is it allowed?

There is a driveId property inside ODItemReference, but the API reference said it's read-only (https://dev.onedrive.com/resources/itemReference.htm)

**Comment by aclev** [comment]
Hi @vinceplusplus  You are correct the driveId is a read only property and you cannot change it, any property that is read only cannot be changed when updating a resource.
