### ISSUE TITLE
signout    not work?

### ISSUE THREAD

**Issue by baoshiwei** [OneDrive/onedrive-sdk-ios#54]
[self.client signOutWithCompletion:^(NSError *error) {
        self.client = nil;
        if (error) {
            NSLog(@"注销失败");
        }else{
            NSLog(@"注销成功");
        }
    }];

I wait a long time ,but  signOut not work ,and can't see the NSLog .I also change wifi to Cellular network，not work too.
SDK version 1.0.5
my Cellular network and wifi is in China

**Comment by aclev** [comment]
Hi @baoshiwei Can you call `[ODClient setLogLevel:ODLogWarn]` before you sign out and let me know what the SDK logs?

**Comment by baoshiwei** [comment]
I try again,in the morning ,sign out work.   I will try it in the afternoon again,the same time of yesterday ,if not work again,I will call [ODClient setLogLevel:ODLogWarn]

**Comment by baoshiwei** [comment]
I try ,and sign out is OK now,maybe the afternoon of yesterday something was wrong,but the SDK is OK,my English not good. Thank you.  @aclev
