### ISSUE TITLE
Unable to get user details and upload file 

### ISSUE THREAD

**Issue by AniShah** [OneDrive/onedrive-sdk-ios#56]
Hi,

I'm able to authenticate user. But after authentication I want user's primary details. I didn't found any method or parameters of this SDK, through which I can get the details. Current scope is

```
"wl.signin", "wl.offline_access", "onedrive.readonly", "onedrive.readwrite", "onedrive.appfolder"
```

Also, when I'm trying to upload file, I'm getting below error

**OneDrive SDK ERROR : Error from download response Error Domain=com.microsoft.onedrive.errors Code=405 "method not allowed" UserInfo=0x17f5f000 {NSLocalizedDescription=method not allowed, error= invalidRequest : Item does not match expected type}**

I'm using below method:

```
let request = odClient.drive().items(folderId).contentRequest()
let urlPath = NSURL(string: strPath!)
request.uploadFromFile(urlPath) { (item, error) -> Void in
     if(error == nil){
          print("Successfully uploaded")
     }
 }
```

I din't found any help over internet related to this issue. Please guide me

**Comment by aclev** [comment]
Hi @AniShah See #5 for your first question. For your second request, you are trying to upload content to a folder, which is not allowed to upload a new item to a folder you can do :

```
let request = odClient.drive().items(folderId).itemByPath("newFileName").contentRequest()
let urlPath = NSURL(string: strPath!)
request.uploadFromFile(urlPath) { (item, error) -> Void in
     if(error == nil){
          print("Successfully uploaded")
     }
 }
```

**Comment by MiteshiOS** [comment]
Hey @aclev having a same problem unable to upload image and getting error code 405.

    __block ODItem *item = [self itemForIndex:2]; //took 2 for upload image in pictures
    self.item = item ;

    if (self.parentItem && !self.item){
        ODItemContentRequest *contentRequest = [[[[self.client drive] items:self.parentItem.id] itemByPath:[self.filePath lastPathComponent]] contentRequest];
        
         [self uploadContentRequest:contentRequest fromData:self.fileModel.fileData];
        
    }
    else if(self.item){
        ODItemContentRequest *contentRequest = [[[[self.client drive] items:self.item.id] contentRequest] ifMatch:self.item.cTag];
        [self uploadContentRequest:contentRequest fromData:self.fileModel.fileData];
    }


     - (void)uploadContentRequest:(ODItemContentRequest*)contentRequest fromData:(NSData *)data
      {
      ODURLSessionUploadTask *task = [contentRequest uploadFromData:data completion:^(ODItem *item, NSError *error){
          [self showUploadResponse:item contentRequest:contentRequest fromData:data error:error];
    }];
       [self.progressController showProgressWithTitle:[NSString stringWithFormat:@"Uploading!"] progress:task.progress];
    }

     - (void)showUploadResponse:(ODItem *)item
            contentRequest:(ODItemContentRequest*)request
                   fromData:(NSData *)fileData
                     error:(NSError *)error
     {
    [self.progressController hideProgress];
    UIAlertController *responseController = nil;
    if (error){
        responseController = [UIAlertController alertControllerWithTitle:@"Fialed To Upload item" message:nil preferredStyle:UIAlertControllerStyleAlert];
        UIAlertAction *tryAgain = [UIAlertAction actionWithTitle:@"Try Again" style:UIAlertActionStyleDefault handler:^(UIAlertAction *action){
            [self uploadContentRequest:request fromData:self.fileModel.fileData];
        }];
        
        UIAlertAction *ok = [UIAlertAction actionWithTitle:@"OK" style:UIAlertActionStyleDefault handler:^(UIAlertAction *action){}];
        
        [responseController addAction:tryAgain];
        [responseController addAction:ok];
    }
    else {
        NSString *title = [NSString stringWithFormat:@"Uploaded %@ !", item.name];
        NSString *message = [NSString stringWithFormat:@"Item Id : %@", item.id];
        responseController = [UIAlertController alertControllerWithTitle:title message:message preferredStyle:UIAlertControllerStyleAlert];
        UIAlertAction *ok = [UIAlertAction actionWithTitle:@"OK" style:UIAlertActionStyleDefault handler:^(UIAlertAction *action){
            if (self.itemSaveCompletion){
                self.itemSaveCompletion(item);
            }
            dispatch_async(dispatch_get_main_queue(), ^(){
                [self.navigationController popViewControllerAnimated:YES];
            });
        }];
        
        [responseController addAction:ok];
    }
    
    dispatch_async(dispatch_get_main_queue(), ^(){
        [self presentViewController:responseController animated:YES completion:nil];
    });
      }
Please help me on this what i am doing wrong.
This is error description.

  Error from download response Error Domain=com.microsoft.onedrive.errors Code=405 "method not allowed" UserInfo={error= invalidRequest : Item does not match expected type, NSLocalizedDescription=method not allowed}

**Comment by aclev** [comment]
Hi @MiteshiOS I'm no longer an active maintainer/contributor to the project.  I think @kevklam can help you out here.

However, from first glance it looks like your first content request  might be incorrect.

```
if (self.parentItem && !self.item){
    ODItemContentRequest *contentRequest = [[[[self.client drive] items:self.parentItem.id] itemByPath:[self.filePath lastPathComponent]] contentRequest];
    
     [self uploadContentRequest:contentRequest fromData:self.fileModel.fileData];
    
}
```
if `[self.filePath lastPathComponent]` doesn't return a valid filename the request would fail. See https://dev.onedrive.com/items/upload_put.htm
