### ISSUE TITLE
Can't be used with OneDrive business accounts

### ISSUE THREAD

**Issue by todddcls** [OneDrive/onedrive-sdk-ios#63]
After logging in with a OneDrive business, making any request results in an assert failure in ODRequestBuilder initWithURL.  Here's the callstack when used with the example explorer app.

2015-11-23 12:07:52.297 iOSExplorer[72640:1748960] **\* Assertion failure in -[ODDriveRequestBuilder initWithURL:client:], /Users/tkr/Downloads/onedrive-sdk-ios/OneDriveSDK/OneDriveCoreSDK/Core/ODRequestBuilder.m:29
2015-11-23 12:07:52.304 iOSExplorer[72640:1748960] **\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: url'
**\* First throw call stack:
(
    0   CoreFoundation                      0x000000010aceef45 **exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x000000010a768deb objc_exception_throw + 48
    2   CoreFoundation                      0x000000010aceedaa +[NSException raise:format:arguments:] + 106
    3   Foundation                          0x000000010a3b55ee -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
    4   iOSExplorer                         0x000000010a1931f3 -[ODRequestBuilder initWithURL:client:] + 323
    5   iOSExplorer                         0x000000010a176118 -[ODClient(HelperMethods) drive] + 136
    6   iOSExplorer                         0x000000010a11c779 -[ODXItemCollectionViewController loadChildren] + 297
    7   iOSExplorer                         0x000000010a11bebf __47-[ODXItemCollectionViewController signInAction]_block_invoke + 143
    8   iOSExplorer                         0x000000010a17265f __72+[ODClient(Authentication) authenticatedClientWithAppConfig:completion:]_block_invoke + 95
    9   iOSExplorer                         0x000000010a173d22 -[ODClient(Authentication) onAuthenticationCompletionWithError:authProvider:httpProvider:completion:] + 338
    10  iOSExplorer                         0x000000010a172fdb __103-[ODClient(Authentication) authenticateWithAuthProvider:httpProvider:logger:viewController:completion:]_block_invoke + 91
    11  iOSExplorer                         0x000000010a16e0ea __68-[ODBusinessAuthProvider authenticateWithViewController:completion:]_block_invoke_3 + 298
    12  iOSExplorer                         0x000000010a133c88 __145-[ADAuthenticationContext internalAcquireTokenByRefreshToken:clientId:resource:userId:cacheItem:validateAuthority:correlationId:completionBlock:]_block_invoke_2 + 552
    13  iOSExplorer                         0x000000010a13986f __125-[ADAuthenticationContext request:requestData:requestCorrelationId:isHandlingPKeyAuthChallenge:additionalHeaders:completion:]_block_invoke + 3151
    14  iOSExplorer                         0x000000010a156113 -[ADWebRequest completeWithError:andResponse:] + 323
    15  iOSExplorer                         0x000000010a156d70 -[ADWebRequest connectionDidFinishLoading:] + 432
    16  CFNetwork                           0x000000010cde19ae __65-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]_block_invoke + 69
    17  Foundation                          0x000000010a3dd3b8 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK** + 7
    18  Foundation                          0x000000010a3190e5 -[NSBlockOperation main] + 101
    19  Foundation                          0x000000010a2fc036 -[__NSOperationInternal _start:] + 646
    20  Foundation                          0x000000010a2fbc47 __NSOQSchedule_f + 194
    21  libdispatch.dylib                   0x000000010d3de49b _dispatch_client_callout + 8
    22  libdispatch.dylib                   0x000000010d3c48ec _dispatch_queue_drain + 2215
    23  libdispatch.dylib                   0x000000010d3c3e0d _dispatch_queue_invoke + 601
    24  libdispatch.dylib                   0x000000010d3c6a56 _dispatch_root_queue_drain + 1420
    25  libdispatch.dylib                   0x000000010d3c64c5 _dispatch_worker_thread3 + 111
    26  libsystem_pthread.dylib             0x000000010d70f4f2 _pthread_wqthread + 1129
    27  libsystem_pthread.dylib             0x000000010d70d375 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by aclev** [comment]
Hi @todddcls Thanks for reporting the bug, Can you show me how you are setting your appid and redirect urls?
Thanks!

**Comment by todddcls** [comment]
In ODXAppDelegate

```
[ODClient setActiveDirectoryAppId:@"dc1a805f-7c21-48ae-8836-555ffff59a92"
                      redirectURL:@"https://localhost/doculus"
                            flags:@{@"NoThumbnails" : @(YES)}];
```

I didn't see anything in the docs when registering the app that the redirect URL had to be anything specific.  Does it need to be?

**Comment by aclev** [comment]
The redirect URL can be whatever you want, as long as the one used in the SDK is the same as the one you provided in the app registration process.  In the Azure Management Portal did you specify the any permission levels?

**Comment by todddcls** [comment]
I hadn't specified the permissions.  That appears to have been the cause.  Sorry for the bother.

**Comment by aclev** [comment]
If you haven't specified permissions, an error should be returned letting you know not asserting down the line.  I am going to re-open the issue to track the bug. Thanks again!

**Comment by todddcls** [comment]
Yea, that would be helpful.  Thanks again!
