### ISSUE TITLE
Getting problem on share url of file

### ISSUE THREAD

**Issue by James24** [OneDrive/onedrive-sdk-ios#64]
If we send create link request, getting error on response 

ODItemCreateLinkRequest *createLinkRequest = [[ODItemCreateLinkRequest alloc] initWithType:@"view"  URL:[NSURL URLWithString:item.webUrl]                                                                                             options:nil  client:odclient];

 [createLinkRequest executeWithCompletion:^(ODPermission response, NSError error) {
                    NSLog(@"print : %@",response.link);
                    NSLog(@"eroororo%@",error);
                    }];

Result : 
OneDrive SDK ERROR : Error from data task : Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}

**Comment by aclev** [comment]
Hi @James24 to get a sharing link you need to do something like 

```
[odClient drive] items:item.id] createLinkWithType:@"view"] executeWithCompletion:^(ODPemission *response, NSError *error){
// do stuff
}];
```

**Comment by James24** [comment]
thank u @aclev :+1:
