### ISSUE TITLE
Incorrect Date formatter

### ISSUE THREAD

**Issue by fischerdan** [OneDrive/onedrive-sdk-ios#65]
The date's found in the dictionary defining an ODItem dates do not match what the NSDateFormatters used in NSDate+ODSerialization.h.

The current  date strings look like
**2015-11-02T21:09:32Z**
and the formatter is looking for
**yyyy-MM-dd'T'HH:mm:ss.SSSZ**
it should just be
**yyyy-MM-dd'T'HH:mm:ssZ**

**Comment by aclev** [comment]
Hey @fischerdan 
Thanks for reporting the issue, our date formats can sometimes have milliseconds. You can see the current pull request for a fix to handle both cases. 
Thanks!
