### ISSUE TITLE
Support for tvOS requested

### ISSUE THREAD

**Issue by tscholze** [OneDrive/onedrive-sdk-ios#71]
It would be great to use this Pod in a tvOS project. Is this new platform as a new target on your roadmap?

![Pod error](https://cloud.githubusercontent.com/assets/5583469/12563745/0e13d868-c3ac-11e5-9201-82d040e5c8b0.png)

**Comment by jordandobson** [comment]
+1

**Comment by kevklam** [comment]
Unfortunately this is unlikely to happen in the near future. The OAuth flow requires UIWebView, which is not supported on tvOS.

**Comment by tscholze** [comment]
Thanks for you answer!

**Comment by petebarber** [comment]
This app (of mine) may be of interest: https://itunes.apple.com/us/app/photone/id1068952548?mt=8

along with the corresponding blogpost: http://petebarber.blogspot.co.uk/search/label/tvOS%20iOS%20swift%20%22Apple%20TV%22%20OAuth%20OAuth2%20iCloud%20KV%20Key-Value%20Photone%20OneDrive
