### ISSUE TITLE
App is not authenticating for business accounts

### ISSUE THREAD

**Issue by wisvijay** [OneDrive/onedrive-sdk-ios#73]
Hi Team,

I am using this sdk to integrate my app with onedrive cloud. 
I created the appId from [Application Portal](https://apps.dev.microsoft.com). 

I am using the below code snippet for authenticating and login from my app.
`[ODClient setMicrosoftAccountAppId:@"xxxx-xxx-xxx-xxxx-xxxxxx" scopes:@[@"onedrive.readwrite"] ];
    [ODClient setActiveDirectoryAppId:@"xxxx-xxx-xxx-xxxx-xxxxxx"
                          redirectURL:@"urn:ietf:wg:oauth:2.0:oob"
                                flags:@{@"NoThumbnails" : @(YES)}];`

I am unable to login with my business account or personal account. I am getting the below error as response,
`Error raised: 15. Additional Information: Domain: ADAuthenticationErrorDomain ProtocolCode:unauthorized_client Details:AADSTS7xxxxx: Application 'xxxx-xxx-xxx-xxxx-xxxxxx' is not supported for this API version.`

Any one can help me with this? Thanks in advance

**Comment by kevklam** [comment]
Hi @wisvijay,
The application portal you used to register your app is the V2 app portal. Unfortunately, the OneDrive SDK is currently using the Azure Active Directory V1 endpoint to authenticate Business accounts, which is not compatible with apps registered on the V2 app portal.

For instructions on registering your Business app via the V1 app portal, please refer to the following:
https://dev.onedrive.com/app-registration.htm#register-your-app-for-onedrive-for-business
