### ISSUE TITLE
[ODClient authenticatedClientWithCompletion:] never calls completion handler

### ISSUE THREAD

**Issue by formconnect-lefler** [OneDrive/onedrive-sdk-ios#79]
Hi,

We've developed an app which integrates the OneDrive SDK and a customer is experiencing a problem logging in. I am not personally able to reproduce the issue, as the app works correctly on my machine. However, the customer reports that they are presented with the login screen, they enter their credentials, grant our app access to their OneDrive, but then after the login screen closes, nothing happens. There is no error message nor any status update, which would indicate that our app's completion handler is never called.

If it's relevant, the user says he was presented with an option to choose between OneDrive and OneDrive for Business, but states that he does not have a OneDrive for Business account. My company has tested the app with multiple accounts of our own (both OneDrive and OneDrive for Business) and have not experienced any problems. Is there any known reason why the SDK would fail to call the completion handler, and if so, what should we do about it?

**Comment by kevklam** [comment]
Hi @formconnect-lefler,

The major scenario that comes to mind would be if a network or service issue prevented the authentication view controller from getting the final redirect in the OAuth flow, or if the redirect were malformed. There is no timeout on the authentication flow, and it is only terminated either by the user pressing 'cancel' or by detecting a page load with URL matching the redirect URL specified in the authentication request. If the service did not return a redirect, or if the redirect did not match the expected URL, the authentication view controller would not be able to detect that it should terminate and will stay open indefinitely.
