### ISSUE TITLE
 Library not found for -lADALiOS

### ISSUE THREAD

**Issue by baoshiwei** [OneDrive/onedrive-sdk-ios#8]
I download the project，and open the project in Examples(iOSExplorer),and pod install，but  Xcode  still  :"Library not found for -lADALiOS".     Did I miss some steps?    Xcode Version 6.3.1

**Comment by aclev** [comment]
Hi @baoshiwei How did you open the project, when using Cocoapods you must run a pod install and then open the iOSExplorer.xcworkspace not the xcproj.

**Comment by baoshiwei** [comment]
I don't use cocoapods before,my fault.Thank you.
