### ISSUE TITLE
Search API is returning 0 results for Business User

### ISSUE THREAD

**Issue by pavanSaberjack** [OneDrive/onedrive-sdk-ios#88]
Search API is working well with personal account. But for business user (account type : ODADAccount) it always returning 0 results lately.  

_Note:_ There few files with name "abc"
Code: 
NSString *itemId = @"root";
ODItemSearchRequest *req = [[[self.client.drive items:itemId] searchWithQ:@"abc"] request];
[req executeWithCompletion:^(ODCollection *response, ODItemSearchRequest *nextRequest, NSError *error) {
}];

**Comment by kevklam** [comment]
@pavanSaberjack Thanks for reporting this, I am following up with the service team.

**Comment by kevklam** [comment]
Looks like this is a known issue on service side. The fix should be rolling out in the next few weeks, I will update here when it is fully deployed.

Thanks,
Kevin

**Comment by kevklam** [comment]
The fix for this should be deployed.
