### ISSUE TITLE
 The app alway prompts to login when start up

### ISSUE THREAD

**Issue by lidoapps** [OneDrive/onedrive-sdk-ios#9]
Although i have signed in, the app prompt to login when start up

[ODClient loadCurrentClient] alway returns nil

**Comment by James24** [comment]
Hi @lidoapps  

In app delegate didfinish launch method 

replace the line 
[ODClient setMicrosoftAccountAppId:@"0000000048160AF8" scopes:@[@"onedrive.readwrite"] ];

with
 [ODClient setMicrosoftAccountAppId:@"0000000048160AF8" scopes:@[@"wl.signin,wl.offline_access,onedrive.readwrite"] ];

**Comment by lidoapps** [comment]
Thanks @James24 
It works

**Comment by James24** [comment]
Welcome :+1:
